# Generated by Django 4.1.5 on 2023-01-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('institution', models.CharField(max_length=200)),
                ('tags', models.CharField(choices=[('Univerisity', 'University'), ('Company', 'Company'), ('Startup', 'Startup')], default='Univerisity', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('funding', models.CharField(max_length=300)),
                ('application_deadline', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
