# Generated by Django 4.1.5 on 2023-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
